[workspace]
authors = ["Li Yao <regulatorygenome@gmail.com>"]
channels = ["conda-forge"]
name = "bioqueue"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "2.0.0"

[dependencies]
python = "3.11.*"
libmagic = "*"
psycopg2 = ">=2.9.12,<3"

[pypi-dependencies]
bioqueue = { path = ".", editable = true }
