# Generated by Django 2.1.1 on 2021-06-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=100)),
                ('prev_par', models.TextField()),
                ('new_par', models.TextField()),
                ('prev_input', models.TextField()),
                ('current_input', models.TextField()),
                ('protocol', models.CharField(max_length=100)),
                ('protocol_ver', models.CharField(max_length=100)),
                ('resume_point', models.SmallIntegerField(default=-1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('required_fields', models.TextField()),
                ('file_support', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileArchives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_ver', models.CharField(max_length=33, null=True)),
                ('inputs', models.TextField()),
                ('files', models.TextField()),
                ('file_md5s', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('shared_with', models.TextField(blank=True, null=True)),
                ('archive_file', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('audit', models.SmallIntegerField(default=0)),
                ('file_id_remote', models.TextField(blank=True, default='ph', null=True)),
                ('raw_files', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_ver', models.CharField(blank=True, max_length=100, null=True)),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('input_file', models.TextField()),
                ('parameter', models.TextField()),
                ('run_dir', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-3, 'Wrong'), (-2, 'ResourceLock'), (-1, 'Finished'), (0, 'Waiting'), (1, 'Running'), (2, 'Interrupted')], default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('resume', models.SmallIntegerField(default=0)),
                ('ter', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('audit', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wait_for', models.SmallIntegerField(choices=[(0, 'Ok'), (1, 'Disk'), (2, 'Memory'), (3, 'CPU'), (4, 'Former'), (5, 'Peer'), (6, 'Virtual Memory')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_notification_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_hash', models.CharField(db_index=True, max_length=50)),
                ('a', models.CharField(blank=True, max_length=50, null=True)),
                ('b', models.CharField(blank=True, max_length=50, null=True)),
                ('r', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Disk'), (2, 'Memory'), (3, 'CPU'), (4, 'Virtual Memory')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('api_secret', models.CharField(default=uuid.uuid4, max_length=64)),
                ('upload_folder', models.CharField(default='', max_length=1024)),
                ('notification_enabled', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_delegate_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_profile_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('ver', models.CharField(max_length=33, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_protocollist_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=50)),
                ('mem', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=50)),
                ('own', models.CharField(default='sys', max_length=50)),
                ('lock', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file_path', models.TextField()),
                ('inner_path', models.TextField()),
                ('attribute', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QueueDB.Experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_sample_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=50)),
                ('parameter', models.TextField()),
                ('specify_output', models.CharField(blank=True, max_length=50, null=True)),
                ('hash', models.CharField(max_length=50)),
                ('step_order', models.SmallIntegerField(default=1)),
                ('force_local', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_hash', models.CharField(db_index=True, max_length=50)),
                ('input', models.CharField(blank=True, max_length=50, null=True)),
                ('output', models.CharField(blank=True, max_length=50, null=True)),
                ('mem', models.CharField(blank=True, max_length=50, null=True)),
                ('vrt_mem', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('lock', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_virtualenvironment_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queuedb_workspace_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='step',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QueueDB.VirtualEnvironment'),
        ),
        migrations.AddField(
            model_name='step',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueueDB.ProtocolList'),
        ),
        migrations.AddField(
            model_name='step',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_step_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueueDB.ProtocolList'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_job_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QueueDB.Workspace'),
        ),
        migrations.AddField(
            model_name='filearchives',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QueueDB.Job'),
        ),
        migrations.AddField(
            model_name='filearchives',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueueDB.ProtocolList'),
        ),
        migrations.AddField(
            model_name='filearchives',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_filearchives_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audition',
            name='related_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueueDB.Job'),
        ),
        migrations.AddField(
            model_name='audition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_audition_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
