# Generated by Django 3.2.24 on 2026-10-04 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QueueDB', '0052_virtualenvironment_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_read', models.SmallIntegerField(choices=[(0, 'Deny'), (1, 'Allow')], default=1)),
                ('allow_write', models.SmallIntegerField(choices=[(0, 'Deny'), (1, 'Allow')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_ver', models.CharField(max_length=33, null=True)),
                ('inputs', models.TextField()),
                ('files', models.TextField()),
                ('file_md5s', models.TextField()),
                ('raw_files', models.TextField(blank=True, null=True)),
                ('audit', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('archive_file', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('shared_with', models.TextField(blank=True, null=True)),
                ('file_id_remote', models.TextField(blank=True, default='ph', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtocolShortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('href_template', models.TextField(help_text='url template, may include {id} placeholder for job id')),
                ('params_template', models.TextField(blank=True, help_text='optional extra path or query, may include {id}', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1)),
            ],
            options={
                'ordering': ['protocol', 'order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('comment', models.TextField()),
                ('is_master', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('ssh_connection', models.CharField(blank=True, help_text='Provide ssh connection info for fabric if this is a remote node', max_length=1024, null=True)),
                ('ssh_user', models.CharField(blank=True, help_text='SSH user', max_length=1024, null=True)),
                ('ssh_key', models.CharField(blank=True, help_text='SSH private key file', max_length=2048, null=True)),
                ('cluster_manager', models.SmallIntegerField(choices=[(0, 'Local'), (1, 'Slurm')], default=0, help_text='Specify the cluster manager if this node is from a cluster')),
                ('cluster_manager_path', models.CharField(blank=True, default='', max_length=2048, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='filearchives',
            name='job',
        ),
        migrations.RemoveField(
            model_name='filearchives',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='filearchives',
            name='user',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('QueueDB.virtualenvironment',),
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('QueueDB.protocollist',),
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='reference',
            name='user_id',
        ),
        migrations.AddField(
            model_name='audition',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audition',
            name='job_ver',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='array_setting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='insitu',
            field=models.SmallIntegerField(choices=[(0, 'ex situ'), (1, 'in situ')], default=0, help_text='Rerun the job in the same folder?'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_executable',
            field=models.SmallIntegerField(choices=[(0, 'no'), (1, 'yes')], default=1, editable=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_gpu_job',
            field=models.SmallIntegerField(choices=[(0, 'CPU job'), (1, 'GPU job')], default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='locked',
            field=models.SmallIntegerField(choices=[(1, 'Locked'), (0, 'Not locked')], default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='parent_job',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QueueDB.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='version',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'Hide'), (1, 'Visible'), (2, 'Visible in workspace')], default=1),
        ),
        migrations.AddField(
            model_name='prediction',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='archive_folder',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_reference_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='step',
            name='cpu_prior',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='step',
            name='disk_prior',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='step',
            name='gpu_step',
            field=models.SmallIntegerField(choices=[(0, 'CPU'), (1, 'GPU')], default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='mem_prior',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='step',
            name='step_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='version_check',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='virtualenvironment',
            name='activation_command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualenvironment',
            name='ve_type',
            field=models.CharField(choices=[('conda', 'conda'), ('venv', 'venv')], default='conda', max_length=10),
        ),
        migrations.AlterField(
            model_name='audition',
            name='related_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QueueDB.job'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_audition_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='audit',
            field=models.SmallIntegerField(choices=[(0, 'Ok'), (1, 'Input/Parameters changed'), (2, 'Protocol/Reference changed'), (3, 'Output modified outside of the platform')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='parameter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='run_dir',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.SmallIntegerField(choices=[(-3, 'Failed'), (-2, 'Waiting for resources'), (-1, 'Finished'), (0, 'Waiting'), (1, 'Running'), (2, 'Interrupted')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_job_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QueueDB.workspace'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_notification_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upload_folder',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='protocollist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_protocollist_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queuedb_sample_related', to='QueueDB.experiment'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_sample_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='step',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QueueDB.virtualenvironment'),
        ),
        migrations.AlterField(
            model_name='step',
            name='software',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='step',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_step_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtualenvironment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_virtualenvironment_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_workspace_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='virtualenvironment',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_name'),
        ),
        migrations.DeleteModel(
            name='FileArchives',
        ),
        migrations.AddField(
            model_name='protocolshortcut',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_protocolshortcut_related', to='QueueDB.protocollist'),
        ),
        migrations.AddField(
            model_name='protocolshortcut',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_protocolshortcut_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filearchive',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QueueDB.job'),
        ),
        migrations.AddField(
            model_name='filearchive',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queuedb_filearchive_related', to='QueueDB.protocollist'),
        ),
        migrations.AddField(
            model_name='filearchive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_filearchive_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crossaccess',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crossaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuedb_crossaccess_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='slave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='QueueDB.slave'),
        ),
        migrations.AddIndex(
            model_name='protocolshortcut',
            index=models.Index(fields=['protocol', 'order'], name='shortcut_protocol_order'),
        ),
    ]
