from django.urls import include, path

from .views import archives
from .views import auth
from .views import dag
from .views import environments
from .views import jobs
from .views import protocols
from .views import references
from .views import workspaces

app_name = "ui3"

urlpatterns = [
    path("login/", auth.login_view, name="login"),
    path("logout/", auth.logout_view, name="logout"),
    path("register/", auth.register_view, name="register"),
    path("account/", auth.account_view, name="account"),
    path("account/clean-folders/", auth.clean_folders_view, name="clean_folders"),
    path("", jobs.job_list, name="home"),
    path("jobs/", jobs.job_list, name="jobs"),
    path("jobs/new/", jobs.job_create, name="job_create"),
    path("jobs/new/batch/", jobs.job_create_batch, name="job_create_batch"),
    path("jobs/new/array/", jobs.job_create_array, name="job_create_array"),
    path("jobs/new/parameter-scaffold/", jobs.parameter_scaffold, name="parameter_scaffold"),
    path("jobs/new/workspace-uploads/", jobs.workspace_uploads, name="workspace_uploads"),
    path("jobs/new/results-picker/", jobs.job_results_picker, name="job_results_picker"),
    path("jobs/bulk/", jobs.job_bulk, name="job_bulk"),
    path("jobs/migrate/", jobs.job_migrate, name="job_migrate"),
    path("jobs/migrate/search/", jobs.job_migrate_search, name="job_migrate_search"),
    path("jobs/running-count/", jobs.running_count, name="running_count"),
    path("jobs/options/protocols/", jobs.protocol_options, name="protocol_options"),
    path("jobs/options/workspaces/", jobs.workspace_options, name="workspace_options"),
    path("jobs/options/runners/", jobs.runner_options, name="runner_options"),
    path("jobs/<int:pk>/rerun/", jobs.job_rerun, name="job_rerun"),
    path("jobs/<int:pk>/terminate/", jobs.job_terminate, name="job_terminate"),
    path("jobs/<int:pk>/lock/", jobs.job_lock, name="job_lock"),
    path("jobs/<int:pk>/visibility/", jobs.job_visibility, name="job_visibility"),
    path("jobs/<int:pk>/gpu/", jobs.job_gpu, name="job_gpu"),
    path("jobs/<int:pk>/mark-wrong/", jobs.job_mark_wrong, name="job_mark_wrong"),
    path("jobs/<int:pk>/mark-finished/", jobs.job_mark_finished, name="job_mark_finished"),
    path("jobs/<int:pk>/resume/", jobs.job_resume, name="job_resume"),
    path("jobs/<int:pk>/delete/", jobs.job_delete, name="job_delete"),
    path("jobs/<int:pk>/purge/", jobs.job_purge, name="job_purge"),
    path("jobs/<int:pk>/compare/<int:other>/", jobs.job_compare, name="job_compare_pair"),
    path("jobs/<int:pk>/compare/", jobs.job_compare, name="job_compare"),
    path("jobs/<int:pk>/protocol-diff/", jobs.job_protocol_diff, name="job_protocol_diff"),
    path("jobs/<int:pk>/array/", jobs.job_array_children, name="job_array"),
    path("jobs/<int:pk>/archive/", jobs.job_archive, name="job_archive"),
    path("jobs/<int:pk>/history/", jobs.job_history, name="job_history"),
    path("jobs/<int:pk>/rename/", jobs.job_rename, name="job_rename"),
    path("jobs/<int:pk>/dependents/", jobs.job_dependents, name="job_dependents"),
    path("jobs/<int:pk>/dependencies/", jobs.job_dependencies, name="job_dependencies"),
    path("jobs/<int:pk>/workspace/", jobs.job_workspace, name="job_workspace"),
    path("jobs/<int:pk>/runner/", jobs.job_runner, name="job_runner"),
    path("jobs/<int:pk>/edit/<str:field>/", jobs.job_edit_field, name="job_edit_field"),
    path("jobs/<int:pk>/logs/", jobs.job_logs, name="job_logs"),
    path("jobs/<int:pk>/files/", jobs.job_files, name="job_files"),
    path("jobs/<int:pk>/files/download/", jobs.job_file_download, name="job_file_download"),
    path("jobs/<int:pk>/files/preview/", jobs.job_file_preview, name="job_file_preview"),
    path("jobs/<int:pk>/files/rename/", jobs.job_file_rename, name="job_file_rename"),
    path("jobs/<int:pk>/files/delete/", jobs.job_file_delete, name="job_file_delete"),
    path("archives/", archives.archive_list, name="archives"),
    path("protocols/options/environments/", protocols.environment_options, name="environment_options"),
    path("protocols/", protocols.protocol_list, name="protocols"),
    path("protocols/new/", protocols.protocol_create, name="protocol_create"),
    path("protocols/import/", protocols.protocol_import, name="protocol_import"),
    path("protocols/step-row/", protocols.protocol_step_row, name="protocol_step_row"),
    path("protocols/<int:pk>/", protocols.protocol_detail, name="protocol_detail"),
    path("protocols/<int:pk>/export/", protocols.protocol_export, name="protocol_export"),
    path("protocols/<int:pk>/update/", protocols.protocol_update, name="protocol_update"),
    path("protocols/<int:pk>/delete/", protocols.protocol_delete, name="protocol_delete"),
    path("protocols/<int:pk>/clone/", protocols.protocol_clone, name="protocol_clone"),
    path("protocols/<int:pk>/steps/", protocols.step_create, name="step_create"),
    path("steps/<int:pk>/edit/", protocols.step_edit, name="step_edit"),
    path("steps/<int:pk>/delete/", protocols.step_delete, name="step_delete"),
    path("steps/<int:pk>/move/", protocols.step_move, name="step_move"),
    path("protocols/<int:pk>/shortcuts/", protocols.shortcut_create, name="shortcut_create"),
    path("shortcuts/<int:pk>/edit/", protocols.shortcut_edit, name="shortcut_edit"),
    path("shortcuts/<int:pk>/delete/", protocols.shortcut_delete, name="shortcut_delete"),
    path("shortcuts/<int:pk>/toggle/", protocols.shortcut_toggle, name="shortcut_toggle"),
    path("workspaces/", workspaces.workspace_list, name="workspaces"),
    path("workspaces/new/", workspaces.workspace_create, name="workspace_create"),
    path("workspaces/<int:pk>/edit/", workspaces.workspace_edit, name="workspace_edit"),
    path("workspaces/<int:pk>/delete/", workspaces.workspace_delete, name="workspace_delete"),
    path("environments/", environments.environment_list, name="environments"),
    path("environments/new/", environments.environment_create, name="environment_create"),
    path("environments/<int:pk>/edit/", environments.environment_edit, name="environment_edit"),
    path("environments/<int:pk>/delete/", environments.environment_delete, name="environment_delete"),
    path("references/", references.reference_list, name="references"),
    path("references/new/", references.reference_create, name="reference_create"),
    path("references/<int:pk>/edit/", references.reference_edit, name="reference_edit"),
    path("references/<int:pk>/delete/", references.reference_delete, name="reference_delete"),
    path("dag/", dag.dag_page, name="dag"),
    path("dag/graph/", dag.dag_graph, name="dag_graph"),
    path("dag/search/", dag.dag_search, name="dag_search"),
    path("dag/jobs/", dag.dag_jobs, name="dag_jobs"),
    path("ext/", include("ui3.plugins.urls")),
]
