# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='vrt_mem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocollist',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
