# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20170504_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.ProtocolList'),
        ),
    ]
