# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_auto_20170510_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='step_order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
