# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_protocol_step_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='job_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
