# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_queue_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='force_local',
            field=models.SmallIntegerField(default=0),
        ),
    ]
