# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_queue_force_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='force_local',
        ),
        migrations.AddField(
            model_name='protocol',
            name='force_local',
            field=models.SmallIntegerField(default=0),
        ),
    ]
