# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20180106_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='force_local',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
