# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-08-19 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_auto_20180108_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.VirtualEnvironment'),
        ),
    ]
